spring.datasource.url=jdbc:postgresql://localhost:5432/acrm
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=create-drop

spring.flyway.enabled=true
spring.flyway.clean-disabled=false

spring.docker.compose.enabled=false

#logging.level.org.flywaydb=DEBUG
