spring.datasource.url=jdbc:postgresql://localhost:5432/acrm
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.flyway.clean-disabled=true
